### PR TITLE
Support react-test-renderer

### PR DESCRIPTION
**Pull request by Hypnosphi**
See https://github.com/reactjs/react-lifecycles-compat/pull/24#issuecomment-388315328

### CODE REVIEW

**Comment by gaearon** [comment]
Can you also send a PR to React itself to align the behavior of shallow and normal rendering?

**Comment by bvaughn** [comment]
Thanks for the fix and the added tests, @Hypnosphi !

**Comment by bvaughn** [comment]
Published as 3.0.4

**Comment by Hypnosphi** [comment]
Here's React PR https://github.com/facebook/react/pull/12784

**Pull request merged**
