### PR TITLE
Polyfill more aggressively warns about old and new lifecycles

### PR DESCRIPTION
**Pull request by bvaughn**
**This is a proposed 3.0 change.**

The polyfill's current invariants do not cover all combinations of old and new lifecycles, e.g.:
* A component with `static getDerivedStateFromProps` and `componentWillUpdate`, or...
* A component with `getSnapshotBeforeUpdate` and either `componentWillMount` or `componentWillReceiveProps`.

This doesn't matter for older versions of React, but React 16.3+ will not invoke the older lifecycles if either of the newer ones exist- so polyfilled components would likely be subtly broken in this case.

This PR mirrors the DEV warning messaging used in React 16.3+, but as a thrown error. Additional tests have been added as well.

### CODE REVIEW

**Comment by gaearon** [comment]
That would be a major change, right? Even though it didn’t quite work before.

**Comment by bvaughn** [comment]
No. This would be a bugfix.

**Comment by gaearon** [comment]
Broken as in "crashed at init time" or as in "did the thing you probably didn't want"? If it didn't crash then introducing a crash is IMO too disruptive even for people who accidentally relied on broken behavior. (Presumably their code still "worked" to some extent.(

**Comment by bvaughn** [comment]
Broken as in...behaves differently between different versions of React, and in some cases- not executing lifecycle methods as expected.

I could restore the previous behavior and just add a new dev warning for the time being, but that doesn't feel like a great solution either

**Comment by gaearon** [comment]
I think it’s okay to throw but this would need to be a major.

**Comment by bvaughn** [comment]
Yeah, it would surely be okay to throw in a major. I just feel uneasy leaving 2.x with a subtle bug.

Maybe the thing to do would be publish a new warning as 2.0.1 and then release this as 3.

**Comment by gaearon** [comment]
I think that would be best.

**Comment by bvaughn** [comment]
Cool. Thanks for the discussion. I'll hold off merging this until after I've made the 2.x warning release.

**Pull request merged**
