### PR TITLE
“vulnerabilities-removed”

### PR DESCRIPTION
**Pull request by aladin002dz**
Hi, I received github alerts about security vulnerabilities, I changed them as recommended and made the PR,
Cheers.

### CODE REVIEW

**Comment by bvaughn** [comment]
Hm. This PR doesn't look too controversial, but it should not have been merged without a team member's approval. I'm actually surprised to see that being a member of reactjs-org-arabic-translation gives merge permissions to this repository.

**Comment by asantarissy** [comment]
Thanks @bvaughn, team work right 😁
I agree with you, but the fix is very simple and followed the exact steps, I can revert it if it's an issue?

**Comment by bvaughn** [comment]
Out of curiosity, what steps are you referring to?

My concern here is more of a permissions issue. I don't think privileges to one repo should grant privileges to others in the org. I wasn't aware that was how things were setup. I will follow up on that.

I'm not concerned about this PR being merged in specific, since it only affects `devDependencies`.

**Comment by gaearon** [comment]
I reverted.

@asantarissy Please don't merge PRs outside of the translation repo you're maintaining. That permissions are so broad was a mistake. In general, it's always a good idea to talk to maintainers of a specific repository before merging any PRs in it.

**Pull request merged**
